apiVersion: v1
kind: Secret
metadata:
  name: mssql-secret
type: Opaque
stringData:
  SA_PASSWORD: "YourStrong@Passw0rd"
  CONNECTION_STRING: "Server=hospital-db;Database=HospitalManagementSystem;User Id=sa;Password=YourStrong@Passw0rd;Encrypt=False;TrustServerCertificate=True;"
