apiVersion: v1
kind: ConfigMap
metadata:
  name: init-sql-config
data:
  init.sql: |
    -- Paste the content of your init.sql here
    -- Example:
    -- CREATE DATABASE HospitalManagementSystem;
    -- GO
    -- USE HospitalManagementSystem;
    -- GO
    -- ... table definitions ...
